### ISSUE TITLE
No communication.

### ISSUE THREAD

**Issue by hugovw1976** [thomasonw/avr_can#1]
Hi, I working in a arduino board with canbus communication, but I want to replace the Atmega328p chip for Atmega32M1 chip, I found your Arduino Core for ATmegaxxM1/C1 CPUs, I installed and work great, but for some reason I can't run the avr_can examples.
I'm not expert programer, I try to check if the canbus port are in correct pins but can't find in your code where you initialize the TX,RX pins, I found where you #define CAN Can0 but where you define the pins? PC2, PC3.
Thanks.

**Comment by thomasonw** [comment]
@hugovw1976  Hello!  Glad you are finding the work of some use.   On the ATmeagexxM1, the CAN ports are hardwired to PC2 and PC3 (Arduino ports D3 and D4) which are physically on the CPU hardware pins 6 & 7.   Pin 6 (Tx) should be connected to pin #1 on the MPxxxx transceiver, while CPU pin 7 (Rx) needs to go to pin 4 on the transceiver.   If you look at my schematic here you can see how I am using it:
[https://github.com/AlternatorRegulator/alt-CAD](https://github.com/AlternatorRegulator/alt-CAD)

Let me know if this gets you the answer you need, or if there is still a problem.

**Comment by hugovw1976** [comment]
Thanks for your answer, all conection are rigth, I connect the ATmega32M1 to my teensy CAN network (3 teensy 3.1) and can't read or send any message, I asume the ATmega32M1 it's bad because I was able to send and read messages in the teensy network, but I was wrong after check with a logic analizer  the ATmega32M1 it's working but in teensy network I have only errors I believe the teensy can library implement a different can protocol and teensy board can communicate eachother but they are unable to connect to a different CAN units, I connect ATmega32M1 to arduino with CANBUS shield and all work fine, now I need to change all the teensy boards with ATmega32M1.
Thanks for all.

**Comment by thomasonw** [comment]
Hello.

I understand you are still not able to transmit on the teensy CAN network, is that correct?   Which library are you using for the teensy?

One thought I have is make sure both are using the same CAN address type, extended (29 bit) vs. simple (11 bit).  But with a simple test program you should be able to see the messages as well as the ANK from the teensy on your logic analyzer.   Please let me know if you are still having issues, and perhaps post some simple code snippets?

**Comment by hugovw1976** [comment]
After update teensy FlexCan library  I can transmit and receive messages . 
Thanks.

**Comment by thomasonw** [comment]
Ah, very good!  Thanks for clarifying.
