### ISSUE TITLE
begin(baudrate, enablepin) not defined

### ISSUE THREAD

**Issue by Frez-g** [thomasonw/avr_can#3]
Hi, I'm fairly new to this library but it seems like exactly what I need for a project I'm working on. 
The only issue I have at the moment is that I wold like to be able to use the `begin(baudrate, enablepin)` function which is listed in the `howtouse.txt` file among the other constructors but isn't defined anywhere in the `avr_can.h` and `avr_can.cpp` files.
Is there any chance it will be implemented in the near future?

**Comment by thomasonw** [comment]
Hello.  So glad you are finding this lib helpful.  I have been sing it now for several years, and it seems solid.

On the Enable pin:  Last year I made changes to the to make the lib more portable, specifically to allow its use with the default Atmel dev environment.  That required me removing the Arduino specifics, including the Enable pin.  There is an archived release which still has that API, you can find it here: [https://github.com/thomasonw/avr_can/releases](https://github.com/thomasonw/avr_can/releases) 

Will note:  the handling of the Enable pin is very basic:  It simply enabled the transceiver during begin(), no other special processing occurred (ala, lower power modes).  You could do that externally before calling begin(), or use the archived lib with the extra parameter.

Do let me know if this helps you!

**Comment by Frez-g** [comment]
Figured out the easiest way to solve the problem is to enable the pin externally as you suggested.
Thank you for your time.

Keep up the great work!
